language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurrev2.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test substitutes
  - ./manage.py test users