language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="purbeurrev2.settings.travis"

services:
  - postgresql

script:
  - python manage.py test substitutes
  - python manage.py test users