language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt
  - python manage.py makemigrations

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="purbeurreV2.settings.travis"

addons:
  postgresql: "9.6"

services:
  - postgresql

script:
  - python manage.py test substitutes
  - python manage.py test users